# Generated by Django 2.1.5 on 2019-09-09 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Category')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='budget.Project')),
            ],
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='category',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='project',
        ),
        migrations.DeleteModel(
            name='Expenses',
        ),
    ]
